apiVersion: v1
kind: Service
metadata:
  name: nyann-bench-api
  labels: {app.kubernetes.io/name: nyann-bench-api}
spec:
  selector: {app.kubernetes.io/name: nyann-bench-api}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
