apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diffprobe.controllerServiceAccount" . }}
automountServiceAccountToken: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "diffprobe.workerServiceAccount" . }}
automountServiceAccountToken: false
