apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-deployment.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "model-deployment.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
