apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-deployment.fullname" . }}
spec:
  selector:
    {{- include "model-deployment.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
